version: 2

sources:
  - name: raw
    schema: main
    tables:
      - name: accounts
        identifier: raw_accounts

models:
  - name: stg_accounts
    columns:
      - name: account_id
        tests: [not_null, unique]
