version: 2

sources:
  - name: raw
    schema: main
    tables:
      - name: leads
        identifier: raw_leads

models:
  - name: stg_leads
    columns:
      - name: lead_id_clean
        tests: [not_null]
      - name: demo_requested_bool
        tests: [not_null]
