#!/usr/bin/env python3
"""
Clean synthetic marketing leads generated by scripts/generate_raw_leads.py.

This script is intentionally organized as a staged Polars walkthrough. Each
cleaning function owns one family of transformations so it is easy to inspect
and discuss the pipeline piece by piece.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import duckdb
import polars as pl

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DB_PATH = REPO_ROOT / "data" / "raw_leads.duckdb"
DEFAULT_OUTPUT_PATH = REPO_ROOT / "data" / "clean_leads.parquet"
DEFAULT_TABLE = "raw_leads"

KNOWN_CHANNELS = [
    "paid_search",
    "organic",
    "linkedin_ads",
    "webinar",
    "partner",
    "event",
    "email",
    "direct",
    "other",
]
KNOWN_CAMPAIGN_TIERS = [
    "tier1_enterprise",
    "tier2_growth",
    "tier3_smb",
    "pilot",
    "legacy_2019",
    "sunset",
]
KNOWN_REGIONS = ["NA", "EMEA", "APAC", "LATAM"]


def load_raw_leads(db_path: Path, table: str = DEFAULT_TABLE) -> pl.DataFrame:
    """Read the raw DuckDB table into a Polars DataFrame."""
    if not db_path.exists():
        raise FileNotFoundError(
            f"Could not find {db_path}. Run scripts/generate_raw_leads.py first."
        )

    con = duckdb.connect(str(db_path), read_only=True)
    try:
        return con.sql(f"SELECT * FROM {table}").pl()
    finally:
        con.close()


def inspect_raw(df: pl.DataFrame, preview_rows: int) -> None:
    """Print a compact profile of the raw frame before transformations."""
    print("Raw leads")
    print(f"  rows: {df.height:,}")
    print(f"  columns: {df.width:,}")
    print("\nSchema")
    for name, dtype in df.schema.items():
        print(f"  {name}: {dtype}")

    print("\nNull counts")
    print(df.null_count())

    print(f"\nPreview ({preview_rows} rows)")
    print(df.head(preview_rows))


def clean_ids_and_timestamps(df: pl.DataFrame) -> pl.DataFrame:
    """Canonicalize lead IDs where possible and expose timestamp quality flags."""
    lead_id_text = pl.col("lead_id").cast(pl.Utf8).str.strip_chars()
    lead_id_digits = lead_id_text.str.extract(r"(?i)^LD-?(\d{1,8})$", 1)

    return (
        df.with_columns(
            lead_id_digits.alias("_lead_id_digits"),
            pl.col("captured_at").is_null().alias("captured_at_missing"),
        )
        .with_columns(
            pl.col("_lead_id_digits")
            .map_elements(
                lambda value: f"LD-{int(value):08d}" if value is not None else None,
                return_dtype=pl.String,
            )
            .alias("lead_id_clean"),
            lead_id_text.str.contains(r"^LD-\d{8}$").alias("lead_id_was_valid"),
            pl.col("_lead_id_digits").is_null().alias("lead_id_malformed"),
            pl.col("captured_at").dt.date().alias("captured_date"),
            pl.col("captured_at").dt.year().alias("captured_year"),
            pl.col("captured_at").dt.month().alias("captured_month"),
        )
        .drop("_lead_id_digits")
    )


def clean_text_fields(df: pl.DataFrame) -> pl.DataFrame:
    """Normalize company, domain, and job title text while keeping raw columns."""
    company_name_clean = (
        pl.col("company_name_messy")
        .cast(pl.Utf8)
        .str.strip_chars()
        .str.replace_all("™", "")
        .str.replace_all(r"\.$", "")
        .str.replace_all(r"\s+", " ")
        .str.to_lowercase()
    )
    company_domain_clean = (
        pl.col("company_domain_raw")
        .cast(pl.Utf8)
        .str.strip_chars()
        .str.to_lowercase()
        .str.replace(r"^(www|mail)\.", "")
    )
    job_title_clean = (
        pl.col("job_title_raw")
        .cast(pl.Utf8)
        .str.strip_chars()
        .str.replace_all("_", " ")
        .str.replace_all("Markting", "Marketing")
        .str.replace_all("Dir\\.", "Director")
        .str.replace_all(r"\s*/\s*acting$", "")
        .str.replace_all(r"\s*\(interim\)$", "")
        .str.replace_all(r"\s+", " ")
        .str.to_lowercase()
    )

    return df.with_columns(
        company_name_clean.alias("company_name_clean"),
        company_domain_clean.alias("company_domain_clean"),
        job_title_clean.alias("job_title_clean"),
        pl.col("company_name_messy").is_null().alias("company_name_missing"),
        pl.col("company_domain_raw").is_null().alias("company_domain_missing"),
        pl.col("job_title_raw").is_null().alias("job_title_missing"),
    )


def clean_categorical_fields(df: pl.DataFrame) -> pl.DataFrame:
    """Standardize categorical fields and convert reply labels to booleans."""
    marketing_channel_clean = (
        pl.col("marketing_channel")
        .cast(pl.Utf8)
        .str.strip_chars()
        .str.to_lowercase()
        .str.replace_all(r"[\s-]+", "_")
    )
    campaign_tier_clean = (
        pl.col("campaign_tier").cast(pl.Utf8).str.strip_chars().str.to_lowercase()
    )
    region_clean = pl.col("region").cast(pl.Utf8).str.strip_chars().str.to_uppercase()
    reply_clean = (
        pl.col("replied_within_7d").cast(pl.Utf8).str.strip_chars().str.to_lowercase()
    )

    return (
        df.with_columns(
            marketing_channel_clean.alias("marketing_channel_clean"),
            campaign_tier_clean.alias("campaign_tier_clean"),
            region_clean.alias("region_clean"),
            reply_clean.alias("_reply_clean"),
        )
        .with_columns(
            pl.col("marketing_channel_clean")
            .is_in(KNOWN_CHANNELS)
            .not_()
            .alias("marketing_channel_unmapped"),
            pl.col("campaign_tier_clean")
            .is_in(KNOWN_CAMPAIGN_TIERS)
            .not_()
            .alias("campaign_tier_unmapped"),
            pl.when(pl.col("region_clean") == "UNKNOWN")
            .then(None)
            .otherwise(pl.col("region_clean"))
            .alias("region_clean"),
            pl.col("region_clean").is_in(KNOWN_REGIONS).not_().alias("region_unmapped"),
            pl.when(pl.col("_reply_clean").is_in(["yes", "y"]))
            .then(True)
            .when(pl.col("_reply_clean").is_in(["no", "n"]))
            .then(False)
            .otherwise(None)
            .alias("replied_within_7d_bool"),
            pl.col("_reply_clean").is_null().alias("replied_within_7d_missing"),
        )
        .drop("_reply_clean")
    )


def parse_employee_bands(df: pl.DataFrame) -> pl.DataFrame:
    """Turn messy employee-band strings into numeric bounds and size buckets."""
    band = (
        pl.col("employee_band_messy")
        .cast(pl.Utf8)
        .str.strip_chars()
        .str.to_lowercase()
        .str.replace_all(r"\s+to\s+", "-")
        .str.replace_all(r"\s+", "")
    )

    return (
        df.with_columns(band.alias("employee_band_normalized"))
        .with_columns(
            pl.col("employee_band_normalized")
            .is_in(["unknown", "n/a", "seelinkedin"])
            .fill_null(True)
            .alias("employee_band_missing_or_unknown"),
            pl.col("employee_band_normalized")
            .str.extract(r"^(\d+)-\d+$", 1)
            .cast(pl.Int64)
            .alias("_employee_range_lower"),
            pl.col("employee_band_normalized")
            .str.extract(r"^\d+-(\d+)$", 1)
            .cast(pl.Int64)
            .alias("_employee_range_upper"),
            pl.col("employee_band_normalized")
            .str.extract(r"^(\d+)\+$", 1)
            .cast(pl.Int64)
            .alias("_employee_plus_lower"),
            pl.col("employee_band_normalized")
            .str.extract(r"^~(\d+)$", 1)
            .cast(pl.Int64)
            .alias("_employee_approx"),
            pl.col("employee_band_normalized")
            .str.extract(r"^(\d+)$", 1)
            .cast(pl.Int64)
            .alias("_employee_exact"),
        )
        .with_columns(
            pl.coalesce(
                "_employee_range_lower",
                "_employee_plus_lower",
                "_employee_approx",
                "_employee_exact",
            ).alias("employee_count_lower"),
            pl.coalesce(
                "_employee_range_upper",
                "_employee_approx",
                "_employee_exact",
            ).alias("employee_count_upper"),
        )
        .with_columns(
            pl.when(pl.col("employee_count_lower").is_null())
            .then(None)
            .when(pl.col("employee_count_lower") >= 5000)
            .then(pl.lit("enterprise"))
            .when(pl.col("employee_count_upper") <= 50)
            .then(pl.lit("small"))
            .when(pl.col("employee_count_upper") <= 500)
            .then(pl.lit("mid_market"))
            .otherwise(pl.lit("commercial"))
            .alias("employee_size_bucket")
        )
        .drop(
            [
                "_employee_range_lower",
                "_employee_range_upper",
                "_employee_plus_lower",
                "_employee_approx",
                "_employee_exact",
            ]
        )
    )


def clean_numeric_measures(df: pl.DataFrame) -> pl.DataFrame:
    """Expose numeric missingness and cap extreme session lengths for modeling."""
    session = pl.col("web_session_seconds")
    lead_score = pl.col("lead_score")

    return df.with_columns(
        session.is_null().alias("web_session_seconds_missing"),
        (session > 86_400).fill_null(False).alias("web_session_seconds_outlier"),
        pl.when(session.is_null())
        .then(None)
        .when(session < 0)
        .then(0.0)
        .when(session > 86_400)
        .then(86_400.0)
        .otherwise(session)
        .alias("web_session_seconds_clean"),
        lead_score.is_null().alias("lead_score_missing"),
        pl.when(lead_score.is_null())
        .then(None)
        .when(lead_score < 0)
        .then(0.0)
        .when(lead_score > 100)
        .then(100.0)
        .otherwise(lead_score)
        .alias("lead_score_clean"),
        pl.col("demo_requested").cast(pl.Boolean).alias("demo_requested_bool"),
    )


def clean_leads(df: pl.DataFrame) -> pl.DataFrame:
    """Run all staged cleaning transformations."""
    return (
        df.pipe(clean_ids_and_timestamps)
        .pipe(clean_text_fields)
        .pipe(clean_categorical_fields)
        .pipe(parse_employee_bands)
        .pipe(clean_numeric_measures)
    )


def validate_cleaned(raw: pl.DataFrame, cleaned: pl.DataFrame) -> None:
    """Fail fast when the cleaned dataset violates core expectations."""
    expected_columns = {
        "lead_id_clean",
        "captured_at_missing",
        "company_name_clean",
        "company_domain_clean",
        "job_title_clean",
        "marketing_channel_clean",
        "campaign_tier_clean",
        "region_clean",
        "replied_within_7d_bool",
        "employee_count_lower",
        "employee_count_upper",
        "employee_size_bucket",
        "web_session_seconds_clean",
        "lead_score_clean",
        "demo_requested_bool",
    }
    missing = expected_columns - set(cleaned.columns)
    if missing:
        raise ValueError(f"Cleaned data is missing expected columns: {sorted(missing)}")
    if cleaned.height != raw.height:
        raise ValueError(f"Expected {raw.height} rows, got {cleaned.height}")
    if "True_Consumer_Sentiment" in cleaned.columns:
        raise ValueError("True_Consumer_Sentiment must not appear in cleaned data")

    invalid_scores = cleaned.filter(
        pl.col("lead_score_clean").is_not_null()
        & ~pl.col("lead_score_clean").is_between(0, 100)
    )
    if invalid_scores.height:
        raise ValueError("lead_score_clean contains values outside [0, 100]")

    invalid_sessions = cleaned.filter(
        pl.col("web_session_seconds_clean").is_not_null()
        & (pl.col("web_session_seconds_clean") < 0)
    )
    if invalid_sessions.height:
        raise ValueError("web_session_seconds_clean contains negative values")


def write_cleaned_parquet(df: pl.DataFrame, output_path: Path) -> Path:
    """Write cleaned leads to Parquet."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    df.write_parquet(output_path)
    return output_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Clean raw marketing leads with Polars.")
    parser.add_argument(
        "--db-path",
        type=Path,
        default=DEFAULT_DB_PATH,
        help=f"Input DuckDB file (default: {DEFAULT_DB_PATH})",
    )
    parser.add_argument(
        "--table",
        default=DEFAULT_TABLE,
        help=f"Input DuckDB table (default: {DEFAULT_TABLE})",
    )
    parser.add_argument(
        "--output-path",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help=f"Output Parquet file (default: {DEFAULT_OUTPUT_PATH})",
    )
    parser.add_argument(
        "--preview-rows",
        type=int,
        default=5,
        help="Number of rows to print before and after cleaning.",
    )
    parser.add_argument(
        "--skip-inspect",
        action="store_true",
        help="Skip raw schema/null/sample printing.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    raw = load_raw_leads(args.db_path.resolve(), args.table)
    if not args.skip_inspect:
        inspect_raw(raw, args.preview_rows)

    cleaned = clean_leads(raw)
    validate_cleaned(raw, cleaned)
    out = write_cleaned_parquet(cleaned, args.output_path.resolve())

    print(f"\nWrote cleaned leads to {out}")
    print(f"  rows: {cleaned.height:,}")
    print(f"  columns: {cleaned.width:,}")
    print(f"\nCleaned preview ({args.preview_rows} rows)")
    print(cleaned.head(args.preview_rows))


if __name__ == "__main__":
    main()
